'\" t
.\"     Title: \fBapper\fR
.\"    Author: Daniel Nicoletti <dantti12@gmail.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 28-11-2016
.\"    Manual: Manuale dell'utente di Apper
.\"    Source: apper 0.9.3
.\"  Language: Italian
.\"
.TH "\FBAPPER\FR" "1" "28\-11\-2016" "apper 0.9.3" "Manuale dell'utente di Apper"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOME"
apper \- Un\*(Aqapplicazione e un gestore di pacchetti che usa PackageKit
.SH "SINOSSI"
.HP \w'\fBapper\fR\ 'u
\fBapper\fR [\fB\-\-updates\fR] [\fB\-\-settings\fR] [\fB\-\-backend\-details\fR] [\fB\-\-type\fR\fI tipo MIME\fR] [\fB\-\-name\fR\fI nome\fR] [\fB\-\-file\fR\fI file\fR] [\fB\-\-resource\fR\fI carattere\fR] [\fB\-\-catalog\fR\fI file\fR]
.SH "DESCRIZIONE"
.PP
Apper \(`e un\*(Aqinterfaccia per PackageKit
.PP
Apper \(`e in grado di gestire pacchetti, applicazioni e aggiornamenti in modo indipendente dalla distribuzione grazie al progetto PackageKit\&.
.PP
Viene fornita agli utenti
Linux\(rg
un\*(Aqunica applicazione da imparare e usare, qualsiasi distribuzione essi usino\&.
.SH "OPZIONI"
.PP
\fB\-\-updates\fR
.RS 4
Mostra gli aggiornamenti disponibili
.RE
.PP
\fB\-\-settings\fR
.RS 4
Mostra la pagina di configurazione di Apper\&.
.RE
.PP
\fB\-\-backend\-details\fR
.RS 4
Mostra informazioni sul motore che PackageKit usa al momento\&.
.RE
.PP
\fB\-\-type\fR \fItipo MIME\fR
.RS 4
Chiama l\*(Aqinstallatore del tipo MIME\&.
.RE
.PP
\fB\-\-name\fR \fInome\fR
.RS 4
Installa il pacchetto col nome
\fInome\fR\&.
.RE
.PP
\fB\-\-file\fR \fIfile\fR
.RS 4
Installa il pacchetto che fornisce il file
\fIfile\fR\&.
.RE
.PP
\fB\-\-resource\fR \fIcarattere\fR
.RS 4
Installa una risorsa di caratteri\&.
.RE
.PP
\fB\-\-catalog\fR \fIfile\fR
.RS 4
Installa il catalogo del pacchetto nel
\fIfile\fR\&.
.RE
.SH "VEDI ANCHE"
.RS 4
Puoi trovare pi\(`u informazioni su Apper nel \m[blue]\fBsito web di Apper\fR\m[]\&\s-2\u[1]\d\s+2\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.SH "AUTORI"
.PP
Il responsabile di Apper \(`e Daniel Nicoletti
<dantti12@gmail\&.com>; Questa pagina di manuale \(`e stata scritta da Matthias Klumpp
<matthias@tenstral\&.net>\&.
.SH "AUTORI"
.PP
\fBDaniel Nicoletti\fR <\&dantti12@gmail\&.com\&>
.RS 4
Autore.
.RE
.PP
\fBMatthias Klumpp\fR <\&matthias@tenstral\&.net\&>
.RS 4
Autore.
.RE
.SH "NOTE"
.IP " 1." 4
sito web di Apper
.RS 4
\%http://kde-apps.org/content/show.php/Apper?content=84745
.RE
