'\" t
.\"     Title: \fBapper\fR
.\"    Author: Daniel Nicoletti <dantti12@gmail.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 10/10/2011
.\"    Manual: Manual do usu\('ario do KDE
.\"    Source: KDE
.\"  Language: Portuguese (Brazil)
.\"
.TH "\FBAPPER\FR" "1" "10/10/2011" "KDE" "Manual do usu\('ario do KDE"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOME"
apper \- Um gerenciador de aplicativos e pacotes que usa o PackageKit
.SH "SINOPSE"
.HP \w'\fBapper\fR\ 'u
\fBapper\fR [\fB\-\-updates\fR] [\fB\-\-settings\fR] [\fB\-\-backend\-details\fR] [\fB\-\-install\-mime\-type\fR\fI tipo\-MIME\fR] [\fB\-\-install\-package\-name\fR\fI nome\fR] [\fB\-\-install\-provide\-file\fR\fI arquivo\fR] [\fB\-\-install\-font\-resource\fR\fIfonte\fR] [\fB\-\-install\-catalog\fR\fI arquivo\fR] [\fB\-\-remove\-package\-by\-file\fR\fI arquivo\fR] [Op\(,c\(~oes\ Gen\('ericas\ do\ KDE] [Op\(,c\(~oes\ Gen\('ericas\ do\ Qt]
.SH "DESCRIPTION"
.PP
O Apper \('e a interface para
KDE
do PackageKit
.PP
O Apper \('e capaz de gerenciar os pacotes, aplicativos e atualiza\(,c\(~oes em diversas distribui\(,c\(~oes gra\(,cas ao projeto PackageKit\&.
.PP
Ele oferece aos usu\('arios do Linux um aplicativo \('unico que eles podem aprender e usar, seja qual for a distribui\(,c\(~ao que estiverem usando\&.
.SH "OP\(,c\(~oES"
.PP
\fB\-\-updates\fR
.RS 4
Mostra as atualiza\(,c\(~oes dispon\('iveis
.RE
.PP
\fB\-\-settings\fR
.RS 4
Mostra a p\('agina de configura\(,c\(~ao do Apper\&.
.RE
.PP
\fB\-\-backend\-details\fR \fInome\fR
.RS 4
Mostra informa\(,c\(~oes sobre a infraestrutura que o PackageKit est\('a usando no momento\&.
.RE
.PP
\fB\-\-install\-mime\-type\fR \fItipo\-MIME\fR
.RS 4
Invoca o instalador de tipos MIME\&.
.RE
.PP
\fB\-\-install\-package\-name\fR \fInome\fR
.RS 4
Instala o pacote chamado
\fInome\fR\&.
.RE
.PP
\fB\-\-install\-provide\-file\fR \fIarquivo\fR
.RS 4
Instala o pacote que cont\('em o arquivo
\fIarquivo\fR\&.
.RE
.PP
\fB\-\-install\-font\-resource\fR \fIfonte\fR
.RS 4
Instala um determinado recurso de fonte\&.
.RE
.PP
\fB\-\-install\-catalog\fR \fIarquivo\fR
.RS 4
Instala o cat\('alogo de pacotes no
\fIarquivo\fR\&.
.RE
.PP
\fB\-\-remove\-package\-by\-file\fR \fIarquivo\fR
.RS 4
Remove o pacote que cont\('em o arquivo
\fIarquivo\fR\&.
.RE
.SH "VEJA TAMB\('eM"
.PP
Mais informa\(,c\(~oes sobre o Apper podem ser encontradas no
\m[blue]\fBsite do Apper\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTORES"
.PP
O mantenedor do Apper \('e Daniel Nicoletti
<dantti12@gmail\&.com>; Esta p\('agina de manual foi escrita por Matthias Klumpp
<matthias@tenstral\&.net>\&.
.SH "AUTORES"
.PP
\fBDaniel Nicoletti\fR <\&dantti12@gmail\&.com\&>
.RS 4
Autor.
.RE
.PP
\fBMatthias Klumpp\fR <\&matthias@tenstral\&.net\&>
.RS 4
Autor.
.RE
.SH "NOTAS"
.IP " 1." 4
site do Apper
.RS 4
\%http://kde-apps.org/content/show.php/Apper?content=84745
.RE
