'\" t
.\"     Title: \fBapper\fR
.\"    Author: Nicoletti, Daniel <dantti12@gmail.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 28 de novembre de 2016
.\"    Manual: Manual d'usuari de l'Apper
.\"    Source: apper 0.9.3
.\"  Language: Catalan
.\"
.TH "\FBAPPER\FR" "1" "28 de novembre de 2016" "apper 0.9.3" "Manual d'usuari de l'Apper"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
apper \- Una aplicaci\('o i gestor de paquets que utilitza PackageKit
.SH "SINOPSI"
.HP \w'\fBapper\fR\ 'u
\fBapper\fR [\fB\-\-updates\fR] [\fB\-\-settings\fR] [\fB\-\-backend\-details\fR] [\fB\-\-type\fR\fI tipus\-MIME\fR] [\fB\-\-name\fR\fI nom\fR] [\fB\-\-file\fR\fI fitxer\fR] [\fB\-\-resource\fR\fI origen\fR] [\fB\-\-catalog\fR\fI fitxer\fR]
.SH "DESCRIPCI\('O"
.PP
Apper \('es la interf\('icie per a PackageKit
.PP
Apper \('es capa\(,c de gestionar paquets, aplicacions i actualitzacions en una forma de distribuci\('o creuada gr\(`acies al projecte PackageKit\&.
.PP
Proporciona als usuaris de
Linux\(rg
una sola aplicaci\('o que poden aprendre i utilitzar a qualsevol distribuci\('o on es trobin\&.
.SH "OPCIONS"
.PP
\fB\-\-updates\fR
.RS 4
Mostra les actualitzacions disponibles\&.
.RE
.PP
\fB\-\-settings\fR
.RS 4
Mostra la p\(`agina de configuraci\('o de l\*(AqApper\&.
.RE
.PP
\fB\-\-backend\-details\fR
.RS 4
Mostra informaci\('o quant al dorsal que utilitza PackageKit\&.
.RE
.PP
\fB\-\-type\fR \fItipus\-MIME\fR
.RS 4
Crida l\*(Aqinstal\(mdlador de tipus MIME\&.
.RE
.PP
\fB\-\-name\fR \fInom\fR
.RS 4
Instal\(mdla el paquet anomenat
\fInom\fR\&.
.RE
.PP
\fB\-\-file\fR \fIfitxer\fR
.RS 4
Instal\(mdla el paquet que cont\('e el fitxer
\fIfitxer\fR\&.
.RE
.PP
\fB\-\-resource\fR \fIorigen\fR
.RS 4
Instal\(mdla un recurs d\*(Aqorigen\&.
.RE
.PP
\fB\-\-catalog\fR \fIfitxer\fR
.RS 4
Instal\(mdla el cat\(`aleg de paquets al
\fIfitxer\fR\&.
.RE
.SH "VEGEU TAMB\('E"
.RS 4
Podeu trobar m\('es informaci\('o quant a Apper en \m[blue]\fBel lloc web d\*(AqApper\fR\m[]\&\s-2\u[1]\d\s+2\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.SH "AUTORS"
.PP
El mantenidor de l\*(AqApper \('es en Daniel Nicoletti
<dantti12@gmail\&.com>; Aquesta p\(`agina de manual va ser escrita per en Matthias Klumpp
<matthias@tenstral\&.net>\&.
.SH "AUTORS"
.PP
\fBNicoletti, Daniel\fR <\&dantti12@gmail\&.com\&>
.RS 4
Autor.
.RE
.PP
\fBKlumpp, Matthias\fR <\&matthias@tenstral\&.net\&>
.RS 4
Autor.
.RE
.SH "NOTES"
.IP " 1." 4
el lloc web d'Apper
.RS 4
\%http://kde-apps.org/content/show.php/Apper?content=84745
.RE
