'\" t
.\"     Title: \fBapper\fR
.\"    Author: Daniel Nicoletti <dantti12@gmail.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 2016-11-28
.\"    Manual: Apper-Benutzerhandbuch
.\"    Source: apper 0.9.3
.\"  Language: German
.\"
.TH "\FBAPPER\FR" "1" "2016\-11\-28" "apper 0.9.3" "Apper-Benutzerhandbuch"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apper \- Ein Verwaltungsprogramm f\(:ur Anwendungen und Pakete, das PackageKit verwendet
.SH "\(:UBERSICHT"
.HP \w'\fBapper\fR\ 'u
\fBapper\fR [\fB\-\-updates\fR] [\fB\-\-settings\fR] [\fB\-\-backend\-details\fR] [\fB\-\-type\fR\fI mime\-type\fR] [\fB\-\-name\fR\fI name\fR] [\fB\-\-file\fR\fI file\fR] [\fB\-\-resource\fR\fI font\fR] [\fB\-\-catalog\fR\fI file\fR]
.SH "BESCHREIBUNG"
.PP
Apper ist eine Bedienungsoberfl\(:ache zu PackageKit
.PP
Apper kann Pakete, Anwendungen und Aktualisierungen f\(:ur beliebige Distributionen verwalten, indem es PackageKit verwendet\&.
.PP
Es stellt
Linux\(rgbenutzern eine einzige Anwendung zur Verf\(:ugung, deren Bedienung Sie lernen und dann f\(:ur jede beliebige Distribution verwenden k\(:onnen,
.SH "OPTIONEN"
.PP
\fB\-\-updates\fR
.RS 4
Zeigt verf\(:ugbare Aktualisierungen an
.RE
.PP
\fB\-\-settings\fR
.RS 4
\(:Offnet den Einrichtungsdialog von Apper
.RE
.PP
\fB\-\-backend\-details\fR
.RS 4
Zeigt Informationen \(:uber das zurzeit von PackageKit verwendete Backend\&.
.RE
.PP
\fB\-\-type\fR \fImime\-type\fR
.RS 4
Startet das Installationsprogramm f\(:ur MIME\-Typen
.RE
.PP
\fB\-\-name\fR \fIname\fR
.RS 4
Installiert das Paket
\fIname\fR\&.
.RE
.PP
\fB\-\-file\fR \fIfile\fR
.RS 4
Installiert das Paket, das die Datei
\fIfile\fR
bereitgestellt\&.
.RE
.PP
\fB\-\-resource\fR \fIfont\fR
.RS 4
Installiert eine Ressource f\(:ur eine Schrift\&.
.RE
.PP
\fB\-\-catalog\fR \fIfile\fR
.RS 4
Installiert den Paketkatalog in
\fIfile\fR\&.
.RE
.SH "SIEHE AUCH"
.RS 4
Weitere Informationen \(:uber Apper finden Sie auf der \m[blue]\fBApper\-Webseite\fR\m[]\&\s-2\u[1]\d\s+2\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.SH "AUTOREN"
.PP
Der Betreuer von Apper ist Daniel Nicoletti
<dantti12@gmail\&.com>\&. Diese Handbuchseite hat Matthias Klumpp
<matthias@tenstral\&.net>
geschrieben\&.
.SH "AUTOREN"
.PP
\fBDaniel Nicoletti\fR <\&dantti12@gmail\&.com\&>
.RS 4
Autor.
.RE
.PP
\fBMatthias Klumpp\fR <\&matthias@tenstral\&.net\&>
.RS 4
Autor.
.RE
.SH "FU\(ssNOTEN"
.IP " 1." 4
Apper-Webseite
.RS 4
\%http://kde-apps.org/content/show.php/Apper?content=84745
.RE
