/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a packagekitadaptor -i PkInterface.h -l PkInterface /home/dylan/canonical/apper/PkSession/org.freedesktop.PackageKit.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef PACKAGEKITADAPTOR_H
#define PACKAGEKITADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "PkInterface.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.PackageKit.Modify
 */
class ModifyAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.PackageKit.Modify")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.PackageKit.Modify\">\n"
"    <method name=\"InstallPackageFiles\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"xid\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"files\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interaction\"/>\n"
"    </method>\n"
"    <method name=\"InstallProvideFiles\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"xid\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"files\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interaction\"/>\n"
"    </method>\n"
"    <method name=\"InstallCatalogs\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"xid\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"files\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interaction\"/>\n"
"    </method>\n"
"    <method name=\"InstallPackageNames\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"xid\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"packages\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interaction\"/>\n"
"    </method>\n"
"    <method name=\"InstallMimeTypes\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"xid\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"mime_types\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interaction\"/>\n"
"    </method>\n"
"    <method name=\"InstallFontconfigResources\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"xid\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"resources\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interaction\"/>\n"
"    </method>\n"
"    <method name=\"InstallGStreamerResources\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"xid\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"resources\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interaction\"/>\n"
"    </method>\n"
"    <method name=\"InstallResources\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"xid\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"type\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"resources\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interaction\"/>\n"
"    </method>\n"
"    <method name=\"RemovePackageByFiles\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"xid\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"files\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interaction\"/>\n"
"    </method>\n"
"    <method name=\"InstallPrinterDrivers\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"xid\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"resources\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interaction\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ModifyAdaptor(PkInterface *parent);
    virtual ~ModifyAdaptor();

    inline PkInterface *parent() const
    { return static_cast<PkInterface *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void InstallCatalogs(uint xid, const QStringList &files, const QString &interaction);
    void InstallFontconfigResources(uint xid, const QStringList &resources, const QString &interaction);
    void InstallGStreamerResources(uint xid, const QStringList &resources, const QString &interaction);
    void InstallMimeTypes(uint xid, const QStringList &mime_types, const QString &interaction);
    void InstallPackageFiles(uint xid, const QStringList &files, const QString &interaction);
    void InstallPackageNames(uint xid, const QStringList &packages, const QString &interaction);
    void InstallPrinterDrivers(uint xid, const QStringList &resources, const QString &interaction);
    void InstallProvideFiles(uint xid, const QStringList &files, const QString &interaction);
    void InstallResources(uint xid, const QString &type, const QStringList &resources, const QString &interaction);
    void RemovePackageByFiles(uint xid, const QStringList &files, const QString &interaction);
Q_SIGNALS: // SIGNALS
};

/*
 * Adaptor class for interface org.freedesktop.PackageKit.Query
 */
class QueryAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.PackageKit.Query")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.PackageKit.Query\">\n"
"    <method name=\"IsInstalled\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"package_name\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interaction\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"installed\"/>\n"
"    </method>\n"
"    <method name=\"SearchFile\">\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"file_name\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interaction\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"installed\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"package_name\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    QueryAdaptor(PkInterface *parent);
    virtual ~QueryAdaptor();

    inline PkInterface *parent() const
    { return static_cast<PkInterface *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool IsInstalled(const QString &package_name, const QString &interaction);
    bool SearchFile(const QString &file_name, const QString &interaction, QString &package_name);
Q_SIGNALS: // SIGNALS
};

#endif
