'\" t
.\"     Title: \fBapper\fR
.\"    Author: Daniel Nicoletti <dantti12@gmail.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 2016-11-28
.\"    Manual: Gebruikershandleiding voor Apper
.\"    Source: apper 0.9.3
.\"  Language: Dutch
.\"
.TH "\FBAPPER\FR" "1" "2016\-11\-28" "apper 0.9.3" "Gebruikershandleiding voor App"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apper \- Een beheerder van toepassingen en pakketten met behulp van PackageKit
.SH "SAMENVATTING"
.HP \w'\fBapper\fR\ 'u
\fBapper\fR [\fB\-\-updates\fR] [\fB\-\-settings\fR] [\fB\-\-backend\-details\fR] [\fB\-\-type\fR\fI mime\-type\fR] [\fB\-\-name\fR\fI naam\fR] [\fB\-\-file\fR\fI bestand\fR] [\fB\-\-resource\fR\fI lettertype\fR] [\fB\-\-catalog\fR\fI bestand\fR]
.SH "BESCHRIJVING"
.PP
Apper is een interface voor PackageKit
.PP
Apper kan pakketten, toepassingen en het bijwerken beheren op een manier die in verschillende distributies werkt, dankzij het project PackageKit\&.
.PP
Het biedt
Linux\(rg
gebruikers een enkele toepassing die ze kunnen leren en gebruiken in de door hen gebruikte distributie\&.
.SH "OPTIES"
.PP
\fB\-\-updates\fR
.RS 4
Beschikbare zaken voor bijwerken tonen
.RE
.PP
\fB\-\-settings\fR
.RS 4
De instellingenpagina van Apper tonen\&.
.RE
.PP
\fB\-\-backend\-details\fR
.RS 4
Informatie over het gebruik op dit moment van de backend PackageKit tonen\&.
.RE
.PP
\fB\-\-type\fR \fImime\-type\fR
.RS 4
Roep het installatieprogramma van een mime\-type aan\&.
.RE
.PP
\fB\-\-name\fR \fInaam\fR
.RS 4
Pakket met de naam
\fInaam\fR
installeren\&.
.RE
.PP
\fB\-\-file\fR \fIbestand\fR
.RS 4
Pakket dat bestand
\fIbestand\fR
levert installeren\&.
.RE
.PP
\fB\-\-resource\fR \fIlettertype\fR
.RS 4
Een lettertype installeren\&.
.RE
.PP
\fB\-\-catalog\fR \fIbestand\fR
.RS 4
De pakketcatalogus in
\fIbestand\fR
installeren\&.
.RE
.SH "ZIE OOK"
.RS 4
Meer informatie over Apper is te vinden op \m[blue]\fBde website van Apper\fR\m[]\&\s-2\u[1]\d\s+2\&.
.RE
.RS 4
kf5options(7)
.RE
.RS 4
qt5options(7)
.RE
.SH "AUTEURS"
.PP
De onderhouder van Apper is Daniel Nicoletti
<dantti12@gmail\&.com>; Deze manual\-page is geschreven door Matthias Klumpp
<matthias@tenstral\&.net>\&.
.SH "AUTEURS"
.PP
\fBDaniel Nicoletti\fR <\&dantti12@gmail\&.com\&>
.RS 4
Auteur.
.RE
.PP
\fBMatthias Klumpp\fR <\&matthias@tenstral\&.net\&>
.RS 4
Auteur.
.RE
.SH "OPMERKINGEN"
.IP " 1." 4
de website van Apper
.RS 4
\%http://kde-apps.org/content/show.php/Apper?content=84745
.RE
