'\" t
.\"     Title: \fBapper\fR
.\"    Author: Nicoletti, Daniel <dantti12@gmail.com>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 2011. okt\('ober 10.
.\"    Manual: KDE felhaszn\('al\('oi k\('ezik\(:onyv
.\"    Source: K Desktop Environment
.\"  Language: Hungarian
.\"
.TH "\FBAPPER\FR" "1" "2011\&. okt\('ober 10\&." "K Desktop Environment" "KDE felhaszn\('al\('oi k\('ezik\(:onyv"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "N\('EV"
apper \- A PackageKitet haszn\('al\('o alkalmaz\('as\- \('es csomagkezelő
.SH "\('ATTEKINT\('ES"
.HP \w'\fBapper\fR\ 'u
\fBapper\fR [\fB\-\-updates\fR] [\fB\-\-settings\fR] [\fB\-\-backend\-details\fR] [\fB\-\-install\-mime\-type\fR\fI MIME\-t\('ipus\fR] [\fB\-\-install\-package\-name\fR\fI n\('ev\fR] [\fB\-\-install\-provide\-file\fR\fI f\('ajl\fR] [\fB\-\-install\-font\-resource\fR\fI betűk\('eszlet\fR] [\fB\-\-install\-catalog\fR\fI f\('ajl\fR] [\fB\-\-remove\-package\-by\-file\fR\fI f\('ajln\('ev\fR] [\('Altal\('anos\ KDE\ opci\('ok] [\('Altal\('anos\ Qt\ opci\('ok]
.SH "LE\('IR\('AS"
.PP
Az Apper a
KDE
fel\(:ulet a PackageKithez
.PP
Az Apper k\('epes csomagok, alkalmaz\('asok \('es friss\('it\('esek kezel\('es\('ere disztrib\('uci\('of\(:uggetlen m\('odon, h\('ala a PackageKit projektnek\&.
.PP
Egys\('eges fel\(:uletet biztos\('it a Linux felhaszn\('al\('oknak, akik megtanulhatj\('ak \('es haszn\('alhatj\('ak b\('armelyik disztrib\('uci\('on\&.
.SH "OPCI\('OK"
.PP
\fB\-\-updates\fR
.RS 4
El\('erhető friss\('it\('esek megjelen\('it\('ese
.RE
.PP
\fB\-\-settings\fR
.RS 4
Az Apper be\('all\('it\('ooldal\('anak megjelen\('it\('ese\&.
.RE
.PP
\fB\-\-backend\-details\fR \fIn\('ev\fR
.RS 4
Inform\('aci\('ok megjelen\('it\('ese a haszn\('alt PackageKit modulr\('ol\&.
.RE
.PP
\fB\-\-install\-mime\-type\fR \fIMIME\-t\('ipus\fR
.RS 4
A MIME\-t\('ipus telep\('itő megh\('iv\('asa\&.
.RE
.PP
\fB\-\-install\-package\-name\fR \fIn\('ev\fR
.RS 4
A
\fIn\('ev\fR
nevű csomag telep\('it\('ese\&.
.RE
.PP
\fB\-\-install\-provide\-file\fR \fIf\('ajl\fR
.RS 4
A
\fIf\('ajl\fR
nevű f\('ajlt biztos\('it\('o csomag telep\('it\('ese\&.
.RE
.PP
\fB\-\-install\-font\-resource\fR \fIbetűk\('eszlet\fR
.RS 4
Betűk\('eszlet telep\('it\('ese\&.
.RE
.PP
\fB\-\-install\-catalog\fR \fIf\('ajl\fR
.RS 4
A
\fIf\('ajl\fR
nevű f\('ajlban l\('evő csomagkatal\('ogus telep\('it\('ese\&.
.RE
.PP
\fB\-\-remove\-package\-by\-file\fR \fIf\('ajln\('ev\fR
.RS 4
A
\fIf\('ajln\('ev\fR
nevű f\('ajlt tartalmaz\('o csomag elt\('avol\('it\('asa\&.
.RE
.SH "L\('ASD M\('EG"
.PP
Tov\('abbi inform\('aci\('ok tal\('alhat\('ok az Apperről
\m[blue]\fBaz Apper weboldal\('an\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "SZERZŐK"
.PP
Az Apper karbantart\('oja Daniel Nicoletti (<dantti12@gmail\&.com>); Ezt a k\('ezik\(:onyvoldalt Matthias Klumpp (<matthias@tenstral\&.net>) \('irta\&.
.SH "SZERZŐK"
.PP
\fBNicoletti, Daniel\fR <\&dantti12@gmail\&.com\&>
.RS 4
Szerz.
.RE
.PP
\fBKlumpp, Matthias\fR <\&matthias@tenstral\&.net\&>
.RS 4
Szerz.
.RE
.SH "MEGJEGYZ\('ESEK"
.IP " 1." 4
az Apper weboldal\('an
.RS 4
\%http://kde-apps.org/content/show.php/Apper?content=84745
.RE
